<?php
<#assign licenseFirst = "/** ">
<#assign licensePrefix = " * ">
<#assign licenseLast = " */">
<#include "${project.licensePath}">

/**
 * Implements hook_menu().
 */
function ${safe_name}_menu () {
  return array();
}
/**
 * Implements hook_theme().
 */
function ${safe_name}_theme($existing, $type, $theme, $path) {
  return array();
}
/**
 * Implements hook_cron().
 */
function ${safe_name}_cron() {

}