<?php
/**
 * @file
 * @copyright The Royal National Theatre
 * @author John-Paul Drawneek
 */

/**
 * Implements hook_menu().
 *
 * @return array
 *   Menu config
 */
function ${safe_name}_menu() {
  return array();
}
/**
 * Implements hook_theme().
 *
 * @param string $existing
 *   An array of existing implementations that may be used for override
 *   purposes.
 * @param string $type
 *   Whether a theme, module, etc. is being processed.
 * @param string $theme
 *   The actual name of theme, module, etc. that is being being processed.
 * @param string $path
 *   The directory path of the theme or module, so that it doesn't need to be
 *   looked up.
 *
 * @return array
 *   An associative array of theme hook information.
 */
function ${safe_name}_theme($existing, $type, $theme, $path) {
  return array();
}
